# Generated by Django 4.2 on 2024-04-28 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meal_plan_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrazyMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_meal', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('source_url', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='mealplan',
            old_name='meals',
            new_name='meal',
        ),
        migrations.AddField(
            model_name='meal',
            name='food_preferences',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('pescatarian', 'Pescatarian'), ('gluten_free', 'Gluten-Free'), ('dairy_free', 'Dairy-Free')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='title',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='food_preferences',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('pescatarian', 'Pescatarian'), ('gluten_free', 'Gluten-Free'), ('dairy_free', 'Dairy-Free'), ('go_crazy', 'Go Crazy!')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='crazy_meal',
            field=models.ManyToManyField(to='meal_plan_app.crazymeal'),
        ),
    ]
