# Generated by Django 4.2 on 2024-05-02 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='meal_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meal_plan_app.mealplan'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='ingredient_amount',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
