# Generated by Django 4.2 on 2024-04-29 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan_app', '0002_crazymeal_rename_meals_mealplan_meal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='user',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='userProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meal_plan_app.userprofile'),
        ),
    ]
