# Generated by Django 4.2 on 2024-04-29 04:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meal_plan_app', '0003_remove_mealplan_user_mealplan_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='mealplan',
            old_name='userProfile',
            new_name='profile',
        ),
    ]
