# Generated by Django 4.2 on 2024-04-29 04:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan_app', '0004_rename_userprofile_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='food_preferences',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('pescatarian', 'Pescatarian'), ('gluten_free', 'Gluten-Free'), ('dairy_free', 'Dairy-Free')], max_length=12, null=True),
        ),
    ]
