# Generated by Django 4.2 on 2024-04-29 21:46

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan_app', '0005_alter_profile_food_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='crazymeal',
            name='ingredient_amount',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='crazymeal',
            name='ingredients',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='food_preferences',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('pescatarian', 'Pescatarian'), ('gluten_free', 'Gluten-Free'), ('dairy_free', 'Dairy-Free')], max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='food_preferences',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('pescatarian', 'Pescatarian'), ('gluten_free', 'Gluten-Free'), ('dairy_free', 'Dairy-Free')], max_length=55, null=True),
        ),
    ]
