# Generated by Django 4.2 on 2024-04-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan_app', '0006_crazymeal_ingredient_amount_crazymeal_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='ingredient_amount',
            field=models.TextField(null=True),
        ),
    ]
